FROM python:3.10-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

COPY docker/requirements/requirements-train.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY config.py train.py mlflow_logger.py ./

# TODO: Uncomment the command below
CMD ["python", "mlflow_logger.py"]